version: '3'

services: 
  db:
    image: mysql
    container_name: sql
    restart: always
    volumes: 
      - ./sqldata:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE  #  CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'med'
      MYSQL_USER: 'user'

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 3306:3306

  app:
    build: ./
    container_name: app
    environment: 
      - DB=db
      - HOST=db
      - USER=user
      - PASSWORD=pass
    ports: 
      - 3000:3000
    links: 
      - db

  nginx:
    image: nginx
    container_name: NGINX
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    links: 
      - app
    