version: '3'

services: 
  db:
    image: mysql
    container_name: sql
    restart: always
    ports:
      - 3306:3306
    volumes: 
      - ./sqldata:/docker-entrypoint-initdb.d
    cap_add:
      - SYS_NICE  #   CAP_SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'qwe123'
      MYSQL_DATABASE: 'med'
      MYSQL_USER: 'root'

  app:
    build: ./
    container_name: app
    environment: 
      - DB=med
      - HOST=db
      - USER=root
      - PASSWORD=qwe123
    ports: 
      - 3000:3000
    links: 
      - db

  jenkins:
    image: jenkins/jenkins:lts
    container_name: JENKINS
    restart: always
    volumes:
      - ./jenkins/jenkins_home:/var/jenkins_home
    privileged: true
    user: root
    ports:
      - 8080:8080

  nginx:
    image: nginx
    container_name: NGINX
    restart: always
    volumes:
      - ./hosts:/etc/nginx/conf.d
    ports:
      - 8000:8000
      - 80:80
    links:
      - adminer
      - app
      - db
      - jenkins
    